@startuml Class Diagram
title Product Model
Class Product {
    -name:string
    -price:float
    -quantity:int
    --
    +getName():sting
    +getPrice():float
    +getQuantity():int
    --
    +setName(value:string)
    +setPrice(value:float)
    +setQuantity(value:int)
    --
    +Prdoduct(name:string, price:float, quantity:int)
    --
    +getTotalPrice():float
}

Product -up-|> Object: "<<extends>>"

hide empty members

@enduml